# --- Script: chapter_8_contours.R ---
# (Can be in same script)

# Step 1: Ensure terra and swiss_elev_raster exist
pacman::p_load(terra, sf, tidyverse)
# Step 2: Generate contour lines using terra::as.contour()
print("Generating contour lines (can take time)...")
# Input is the elevation raster
# 'nlevels' suggests how many contour levels terra should aim
# for (adjust!)
# 'maxcells' can limit processing on huge rasters if needed
contour_lines_terra <- terra::as.contour(
  swiss_elev_raster, nlevels = 10)
print("Contour lines generated by terra.")

# Step 3: Convert terra's contour output (SpatVector) to an sf object
print("Converting contours to sf object...")
# The |> pipe sends the terra object to the conversion function
contour_lines_sf <- contour_lines_terra |>
  sf::st_as_sf()
print("Conversion complete.")

# Inspect the sf object - it has a 'level' column with elevation
print("--- First few rows of contour sf object ---")
print(head(contour_lines_sf))
print("--- CRS of contours ---")
print(sf::st_crs(contour_lines_sf)) # Should match original
# raster CRS

# Step 4: Map contours with ggplot2
print("Creating contour map...")

contour_map <- ggplot() +
  # Layer 1: Plot the contour lines using geom_sf
  # Map the 'level' column (elevation value) to the color aesthetic
  geom_sf(
    data = contour_lines_sf, 
    aes(color = level), linewidth = 0.3) +
  
  # Use a sequential color scale that matches elevation idea
  # scale_color_viridis_c(option = "mako", ...) works well
  scale_color_viridis_c(
    option = "mako", name = "Elevation (m)") +
  
  # Add labels and theme
  labs(
    title = "Contour Map of Switzerland", 
    caption = "Data: SRTM 30s via geodata") +
  theme_minimal() +
  theme(
    axis.text = element_blank(), 
    panel.grid = element_blank())

# Step 5: Display map
print(contour_map)
print("Contour map generated.")

# Store for later
assign("contour_lines_sf", contour_lines_sf, envir = .GlobalEnv)